export const exercises = [
  ["barbell-bench-press", "Barbell Bench Press", "Classic chest press for upper-body pushing strength.", "strength", "chest", "barbell"],
  ["incline-dumbbell-press", "Incline Dumbbell Press", "Targets upper chest and shoulders with independent arm control.", "strength", "chest", "dumbbells"],
  ["push-up", "Push-Up", "Bodyweight chest and triceps exercise with scalable difficulty.", "strength", "chest", "bodyweight"],
  ["pull-up", "Pull-Up", "Vertical pulling movement for back and arm strength.", "strength", "back", "pull-up bar"],
  ["lat-pulldown", "Lat Pulldown", "Machine-based back exercise emphasizing lats.", "strength", "back", "cable machine"],
  ["barbell-row", "Barbell Row", "Compound pull for back thickness and posterior chain tension.", "strength", "back", "barbell"],
  ["deadlift", "Deadlift", "Full-body hinge movement that develops posterior chain strength.", "strength", "back", "barbell"],
  ["back-squat", "Back Squat", "Primary lower-body compound lift for legs and core.", "strength", "legs", "barbell"],
  ["goblet-squat", "Goblet Squat", "Accessible squat variation using a dumbbell or kettlebell.", "strength", "legs", "dumbbell"],
  ["walking-lunge", "Walking Lunge", "Single-leg exercise for quads, glutes, and balance.", "strength", "legs", "bodyweight"],
  ["romanian-deadlift", "Romanian Deadlift", "Hip hinge focused on hamstrings and glutes.", "strength", "legs", "barbell"],
  ["leg-press", "Leg Press", "Machine-based leg exercise for controlled heavy loading.", "strength", "legs", "leg press machine"],
  ["overhead-press", "Overhead Press", "Standing press for shoulders, triceps, and core stability.", "strength", "shoulders", "barbell"],
  ["lateral-raise", "Lateral Raise", "Isolation movement for side delts and shoulder width.", "strength", "shoulders", "dumbbells"],
  ["face-pull", "Face Pull", "Cable exercise for rear delts and upper-back posture.", "strength", "shoulders", "cable machine"],
  ["biceps-curl", "Biceps Curl", "Arm isolation movement emphasizing elbow flexion.", "strength", "arms", "dumbbells"],
  ["triceps-pushdown", "Triceps Pushdown", "Cable isolation exercise for triceps volume work.", "strength", "arms", "cable machine"],
  ["plank", "Plank", "Static core hold that trains bracing and trunk endurance.", "strength", "core", "bodyweight"],
  ["hanging-knee-raise", "Hanging Knee Raise", "Core and hip-flexor movement performed from a bar.", "strength", "core", "pull-up bar"],
  ["burpee", "Burpee", "Conditioning drill combining squat, plank, and jump patterns.", "conditioning", "full_body", "bodyweight"],
  ["jump-rope", "Jump Rope", "Low-footprint cardio tool for cadence and conditioning.", "cardio", "full_body", "jump rope"],
  ["running", "Running", "Steady-state or interval cardio for endurance and recovery capacity.", "cardio", "legs", "treadmill"],
  ["rowing-machine", "Rowing Machine", "Cardio modality with full-body rhythmic effort.", "cardio", "full_body", "rower"],
  ["cycling", "Cycling", "Bike-based cardio for endurance or interval training.", "cardio", "legs", "stationary bike"],
  ["hip-flexor-stretch", "Hip Flexor Stretch", "Improves front-hip mobility after sitting or leg training.", "flexibility", "legs", "bodyweight"],
  ["hamstring-stretch", "Hamstring Stretch", "Lengthens posterior chain and improves hinge range.", "flexibility", "legs", "bodyweight"],
  ["thoracic-rotation", "Thoracic Rotation", "Mobility drill to improve mid-back rotation.", "mobility", "back", "bodyweight"],
  ["worlds-greatest-stretch", "World's Greatest Stretch", "Dynamic mobility flow for hips, spine, and shoulders.", "mobility", "full_body", "bodyweight"],
  ["cat-cow", "Cat-Cow", "Spinal mobility drill used in warmups and recovery sessions.", "mobility", "core", "bodyweight"],
  ["band-pull-apart", "Band Pull-Apart", "Shoulder activation movement for posture and warmups.", "mobility", "shoulders", "resistance band"],
];
